[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
bytes = "1.4.0"
chrono = "0.4.30"
clap = { version = "4.1.11", features = ["derive"] }
figlet-rs = "0.1.5"
flume = "0.11.0"
futures = "0.3.28"
serde = { version = "1.0.159", features = ["derive", "rc"] }
sled = "0.34.7"
thiserror = "1.0.40"
toml = "0.8.0"
tokio = { version = "1.28.2", features = ["full"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17", features = ["fmt"] }
tracing-appender = "0.2.2"

[[bin]]
name = "node"
path = "src/main.rs"
