[stream]
path = "local_data/node2/streams"

[server]
address = "0.0.0.0:8102"

[node]
id = 2
name = "node2"
address = "0.0.0.0:8202"

[cluster]
max_timeout = 1000
heartbeat_interval = 3000
reconnection_interval = 1000
reconnection_retries = 10
secret = "secret123!"

[[cluster.nodes]]
id = 1
name = "node1"
address = "0.0.0.0:8201"

[[cluster.nodes]]
id = 3
name = "node3"
address = "0.0.0.0:8203"