[stream]
path = "local_data/node3/streams"

[server]
address = "127.0.0.1:8103"

[node]
id = 3
name = "node3"
address = "0.0.0.0:8203"

[cluster]
max_timeout = 1000
heartbeat_interval = 3000
reconnection_interval = 1000
reconnection_retries = 10
secret = "secret123!"
election_timeout_range_from = 150
election_timeout_range_to = 300
required_acknowledgements = "Majority"
state_path = "local_data/node3"

[[cluster.nodes]]
id = 1
name = "node1"
public_address = "127.0.0.1:8101"
internal_address = "0.0.0.0:8201"

[[cluster.nodes]]
id = 2
name = "node2"
public_address = "127.0.0.1:8102"
internal_address = "0.0.0.0:8202"