[stream]
path = "/local_data/streams"

[node]
name = "node1"
address = "0.0.0.0:8100"

[cluster]
max_timeout = 1000
healthcheck_interval = 3000
reconnection_interval = 1000
reconnection_retries = 10

[[cluster.nodes]]
name = "node2"
address = "0.0.0.0:8110"

[[cluster.nodes]]
name = "node3"
address = "0.0.0.0:8120"