[stream]
path = "local_data/node3/streams"

[server]
address = "0.0.0.0:8103"

[node]
name = "node3"
address = "0.0.0.0:8203"

[cluster]
max_timeout = 1000
healthcheck_interval = 3000
reconnection_interval = 1000
reconnection_retries = 10

[[cluster.nodes]]
name = "node1"
address = "0.0.0.0:8201"

[[cluster.nodes]]
name = "node2"
address = "0.0.0.0:8202"